### ISSUE TITLE
The intelligent prompts are not comprehensive, and some symbols cannot be found

### ISSUE THREAD

**Issue by YGXXD** [boocs/unreal-clangd#20]
UE5.4
MacOS M2Pro
Apple Clang 15.0.0
<img width="1482" alt="image" src="https://github.com/user-attachments/assets/ab781218-7c24-4160-9e73-96cee1c6b905">

**Comment by boocs** [comment]
## Wrong clang/clangd version?

1. You can check the clang compiler version by getting the clang path in your .vscode/unreal-clangd/compile_commands.json

Open it up and you should see something like this (ignore the cl.exe name, on Mac it will be clang++)
![image](https://github.com/user-attachments/assets/f0b7f1a5-c501-460f-ad90-7fd2464adcac)

2. I don't know if this works but in your terminal try this(change path to the one found in compile_commands.json):
```
/path/to/clang++ --version
```

3. I believe it will show it as version 16.0.6 (which it should be). You'll need to install 'clangd' 16.0.6 to match with the compiler version.

Make sure to reinstall the 'Unreal Clangd Project' and choose the correct 'clangd' 16.0.6 exec file when it asks.


---

## Incorrect .clangd file setting?

Another reason could be a wrong '.clangd' file setting for Macs. This could be an Intel Mac only problem but it shouldn't be a problem for M2 Macs. This is because this setting treats C++ file extensions as C++ and Objective C++ file extensions as Objective C++. So it shouldn't be a problem to test.

Check your .clangd file and see the line -xc++?
```
# ...
Add:
    - -std=c++20
    - -xc++
    - -Wall
    - -Werror
# ...
```

Try changing it to -xobjective-c++

```
# ...
Add:
    - -std=c++20
    - -xobjective-c++
    - -Wall
    - -Werror
# ...
```
